name: pyBehavior
dependencies:
  - python
  - pyqt
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - anaconda::ipykernel
  - pyyaml
  - h5py
  - scipy
  - pip:
    - nidaqmx
    - python-statemachine
    - paramiko
    - scp