name: pyBehavior
channels:
  - anaconda
  - defaults
dependencies:
  - python
  - pyqt
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - ipykernel
  - pyyaml
  - h5py
  - scipy
  - pip:
    - nidaqmx
    - python-statemachine