name: ni-pyqt
channels:
  - anaconda
  - defaults
dependencies:
  - python
  - pyqt
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - ipykernel
  - pyyaml
  - pip:
    - nidaqmx
    - paramiko